### ISSUE TITLE
rosys.run.sh might return None

### ISSUE THREAD

**Issue by NiklasNeugebauer** [zauberzeug/rosys#42]
rosys.run.sh has the following signature:
```py
async def sh(command: list[str] | str, *,
             timeout: Optional[float] = 1,
             shell: bool = False,
             working_dir: Optional[Path] = None) -> str:
```

However, line 109 may return None:
```py
return await asyncio.wait_for(io_bound(popen), timeout)
```

It should keep to its type hint, which is an easy fix of either checking for None and returning an empty string or changing the signature depending on what should be communicated outward.

**Comment by falkoschindler** [comment]
We will try to find a reproduction for the return value `None` before deciding how to change the implementation or annotation.

**Comment by falkoschindler** [comment]
This has been resolved by #47.

**Comment by NiklasNeugebauer** [comment]
I had a look at this again today and was unable to reproduce it

**Comment by rodja** [comment]
Ok. We'll close it.
