### ISSUE TITLE
Use run.io_bound and run.cpu_bound from NiceGUI to avoid code duplication

### ISSUE THREAD

**Issue by rodja** [zauberzeug/rosys#43]
We have made `run.io_bound` and `run.cpu_bound` available in NiceGUI and should remove the code duplication in RoSys.

**Comment by falkoschindler** [comment]
I had to revert my commit because it broke tests in other projects.
Especially `running_cpu_bound_processes` needs to be updated so that the tests way for completion.
But maybe there are more things to consider.

**Comment by rodja** [comment]
It would be great to have a minimal example to test the problematic cases.
