### ISSUE TITLE
docs issue - links to /robot-brain or /robot-brain.html need to correct to /products/robot-brain

### ISSUE THREAD

**Issue by leonstafford** [zauberzeug/rosys#80]
as per title, example in this section:

https://rosys.io/examples/hardware/#robot-brain

<img width="534" alt="Screenshot 2024-02-07 at 1 50 40 pm" src="https://github.com/zauberzeug/rosys/assets/2066833/b75f44a0-1d07-4f52-9f84-f2c909d68ded">

**Comment by falkoschindler** [comment]
Thanks for pointing this out, @leonstafford!
I fixed the links in https://github.com/zauberzeug/rosys/commit/7a6ac01c64b2f5a53a271d7b4be632e463a73662. The update will be deployed with the next release. 🙂
