### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing'

### ISSUE THREAD

**Issue by zhuoqun-chen** [zauberzeug/rosys#87]
`typing.Self` is included in `python 3.11` and later, thus the import part in the examples, such as `steering`, should add additional check, for example,

```python
try:
    from typing import Self, Sequence
except:
    from typing_extensions import Self, Sequence
```

to be backward compatible. Or you can update the doc and remind users that examples require `3.11` or later.

**Comment by falkoschindler** [comment]
Oh, thanks for pointing this out, @zhuoqun-chen!

We usually use RoSys with Python 3.11, but according to pyproject.toml we allow for Python 3.10 as well.

@rodja What do you think: Should we keep supporting Python 3.10? We'd probably only need to add 3.10 to the pytest workflow and fix some minor issues like importing `Self`.
